import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import '../assets/Pro.css';
import logo from '../assets/images/logo.png';
import man from '../assets/images/man.png';
import video1 from '../assets/images/video1.mp4'; // Ensure this path is correct

export const HomePage = () => {
  const [isLoggedIn, setIsLoggedIn] = useState(false); // Manage login state
  const [userEmail, setUserEmail] = useState(''); // Store user email
  const navigate = useNavigate(); // Hook to programmatically navigate

  const handleLogin = () => {
      // Simulate a login (you should replace this with actual authentication logic)
      setIsLoggedIn(true);
      setUserEmail('user@example.com'); // Replace with the actual logged-in user email
      navigate('/home'); // Redirect to the dashboard or any page you want after login
  };

  const handleLogout = () => {
      // Simulate logout
      setIsLoggedIn(false);
      setUserEmail('');
      navigate('/'); // Redirect to home or login page
  };

  return (
    <>
      <header className="navbar">
            <div className="logo-container">
                <Link to="/">
                    <img src={logo} alt="Logo" className="logo" />
                </Link>
            </div>
            <nav className="nav-menu">
                <ul>
                    <li className="tooltip">
                        <Link to="/">Features</Link>
                        <ul style={{ maxHeight: "651px" }}>
                            <div className="tooltiptext">See our features
                                <li className="sub-menu-item has-introduction" style={{ background: "visible" }}>
                                    <a href="dashboard" className="sub-menu-item">
                                        <i className="icon fa fa-calendar"></i>
                                        <h3>Employee scheduling</h3>
                                        <span className="introduction">Our drag &amp; drop scheduler is fast, quick to learn and free for small teams.</span>
                                    </a>
                                </li>
                                <li className="sub-menu-item has-introduction">
                                    <a href="" className="sub-menu-item"><i className="icon ion ion-ios-clock-outline"></i>
                                        <h3>Time and attendance</h3><span className="introduction">Record the hours your employees are actually on-site with our free time clock station.</span>
                                    </a>
                                </li>
                                <li className="sub-menu-item has-introduction">
                                    <a href="" className="sub-menu-item"><i className="icon fa fa-bar-chart"></i>
                                        <h3>Reporting and payroll</h3><span className="introduction">Track employee hours and their costs in real-time using the data generated by your work schedule.</span>
                                    </a>
                                </li>
                                <li className="sub-menu-item has-introduction">
                                    <a href="" className="sub-menu-item"><i className="icon fa fa-bell-o"></i>
                                        <h3>Reminders and notifications</h3><span className="introduction">Send your employees automated shift reminders, shift change notifications and group messages.</span>
                                    </a>
                                </li>
                                <li className="sub-menu-item has-introduction">
                                    <a href="" className="sub-menu-item"><i className="icon ion ion-android-checkbox-outline"></i>
                                        <h3>Time off management</h3><span className="introduction">Manage time off easily with online requests, assistant managers, notifications and allowance tracking.</span>
                                    </a>
                                </li>
                            </div>
                        </ul>
                    </li>
                    <li className="tooltip">
                        <Link to="/pricing">Pricing</Link>
                        <ul>
                            <span className="tooltiptext">View pricing details
                                <li className="sub-menu-item has-introduction">
                                    <a href="/pricing" className="sub-menu-item"><i className="icon fa fa-rocket"></i>
                                        <h3>Pricing plans</h3><span className="introduction">Choose a pricing plan that works for your team.</span>
                                    </a>
                                </li>
                                <li className="sub-menu-item has-introduction">
                                    <a href="/pricing" className="sub-menu-item"><i className="icon fa fa-gift"></i>
                                        <h3>Free plan for small teams</h3><span className="introduction">Findmyshift will always be free for small teams of up to 5 employees.</span>
                                    </a>
                                </li>
                                <li className="sub-menu-item has-introduction">
                                    <a href="/pricing" className="sub-menu-item"><i className="icon ion ion-ios-clock-outline"></i>
                                        <h3>Free time clock software</h3><span className="introduction">Free, unrestricted access to our web-based time clock system to help track employee hours.</span>
                                    </a>
                                </li>
                                <li className="sub-menu-item has-introduction">
                                    <a href="/pricing" className="sub-menu-item"><i className="icon fa fa-heart-o"></i>
                                        <h3>Try it free for 60 days</h3><span className="introduction">All features are free for your first 60 days. No credit cards, no mailing lists, no surprises.</span>
                                    </a>
                                </li>
                            </span>
                        </ul>
                    </li>
                    <li className="tooltip">
                        <Link to="/Layout">Help</Link>
                        <ul>
                            <span className="tooltiptext">Get support
                                <li className="sub-menu-item has-introduction">
                                    <a href="/Layout" className="sub-menu-item"><i className="icon fa fa-life-ring"></i>
                                        <h3>Knowledge base</h3><span className="introduction">Search for answers to some of the most frequently asked questions.</span>
                                    </a>
                                </li>
                                <li className="sub-menu-item has-introduction">
                                    <a href="/Layout" className="sub-menu-item"><i className="icon ion ion-social-youtube-outline"></i>
                                        <h3>Video guides and webinars</h3><span className="introduction">Watch how it's done (from setup to scheduling) with our step-by-step video guides.</span>
                                    </a>
                                </li>
                                <li className="sub-menu-item has-introduction">
                                    <a href="javascript:void(0);" onClick={() => alert('Contact support')} className="sub-menu-item last">
                                        <i className="icon fa fa-comments-o"></i>
                                        <h3>Contact support</h3><span className="introduction">Call, chat and email our support team between 12am and 10pm (BST), Monday to Friday.</span>
                                    </a>
                                </li>
                            </span>
                        </ul>
                    </li>
                    <li className="tooltip">
                        <Link to="/dashboard">Demo</Link>
                        <span className="tooltiptext">Try the demo</span>
                    </li>
                    {isLoggedIn ? (
                        <li className="tooltip">
                            <span className="tooltiptext">
                                Logged in as {userEmail}
                                <button onClick={handleLogout} className="logout-button">Logout</button>
                            </span>
                        </li>
                    ) : (
                        <li className="tooltip">
                            <Link to="/login" onClick={handleLogin}>Log in</Link>
                            <span className="tooltiptext">Access your account</span>
                        </li>
                    )}
                    <li className="highlight tooltip">
                        <Link to="/dashboard">Create a schedule</Link>
                        <span className="tooltiptext">Start scheduling</span>
                    </li>
                </ul>
            </nav>
        </header>
      <div id="page-content" className="content">
        <header className="main-header">
          <div className="header-images">
            <img
              src={man}
              alt="Man with laptop"
              className="header-image-man"
            />
          </div>
          <div className="wrapper">
            <h1 className="smaller-font">
              <span>Employee scheduling software made simple.</span>
            </h1>
            <div id="introduction">
              <span>
                "Create employee schedules, manage shift requests, track your labor costs and communicate with your employees."
              </span>
            </div>
            <div className="cta-buttons">
              <span className="button-container">
                <Link className="fill-on-hover white" to="/create-an-employee-schedule">Get started</Link>
                <span className="or-text">or</span>
                <br />
                <a className="invert-on-hover green" href="/employee-scheduling-demo" onClick={() => { /* Implement Try function here */ }}>Try the demo</a>
              </span>
            </div>
          </div>
        </header>
        <div className="primary-content">
          <div className="feature-content">
            <div className="wrapper feature video-feature">
              <h2>Scheduling software that's ready for business.</h2>
              <div className="introduction">
                With <a href="/testimonials-and-feedback">19 years of feedback</a> from thousands of managers, we're
                constantly refining our software to meet the needs of real businesses. With over a decade of development,
                Findmyshift is a stable, reliable, and scalable scheduling service for all types of organizations, no matter
                how large or small.
              </div>
              <div className="video-overlay">
                <video className="fullscreen-video" autoPlay loop muted>
                  <source src={video1} type="video/mp4" />
                </video>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="alternate">
        <div className="wrapper feature industries" style={{ textAlign: 'center' }}>
          <h2>Scheduling software for everyone.</h2>
          <div className="industries">
            <a href="/bar-and-restaurant-scheduling">
              <span className="character-container">
                <img
                  loading="lazy"
                  className="character"
                  alt="Chef"
                  src="https://cdn6.findmyshift.com/images/features/industries/chef_x1.png"
                />
              </span>
              <span className="text">Bars, restaurants &amp; cafes</span>
            </a>
            <a href="/call-centre-scheduling">
              <span className="character-container">
                <img
                  loading="lazy"
                  className="character"
                  alt="Call Agent"
                  src="https://cdn6.findmyshift.com/images/features/industries/call-agent_x1.png"
                />
              </span>
              <span className="text">Call centres &amp; support employees</span>
            </a>
            <a href="/charity-and-volunteer-scheduling">
              <span className="character-container">
                <img
                  loading="lazy"
                  className="character"
                  alt="Park Ranger"
                  src="https://cdn6.findmyshift.com/images/features/industries/park-ranger_x1.png"
                />
              </span>
              <span className="text">Charities, non-profits &amp; volunteers</span>
            </a>
            <a href="/cinema-theatre-and-live-event-scheduling">
              <span className="character-container">
                <img
                  loading="lazy"
                  className="character"
                  alt="Cinema Worker"
                  src="https://cdn6.findmyshift.com/images/features/industries/cinema-worker_x1.png"
                />
              </span>
              <span className="text">Cinemas, theatres &amp; live events</span>
            </a>
            <a href="/emergency-worker-scheduling">
              <span className="character-container">
                <img
                  loading="lazy"
                  className="character"
                  alt="Fireman"
                  src="https://cdn6.findmyshift.com/images/features/industries/fireman_x1.png"
                />
              </span>
              <span className="text">Emergency workers &amp; first responders</span>
            </a>
            <a href="/gym-and-fitness-centre-scheduling">
              <span className="character-container">
                <img
                  loading="lazy"
                  className="character"
                  alt="Fitness Instructor"
                  src="https://cdn6.findmyshift.com/images/features/industries/fitness-instructor_x1.png"
                />
              </span>
              <span className="text">Gyms &amp; fitness centres</span>
            </a>
            <a href="/hospitality-scheduling">
              <span className="character-container">
                <img
                  loading="lazy"
                  className="character"
                  alt="Waiter"
                  src="https://cdn6.findmyshift.com/images/features/industries/waiter_x1.png"
                />
              </span>
              <span className="text">Hospitality, hotels &amp; events</span>
            </a>
            <a href="/hospital-and-medical-scheduling">
              <span className="character-container">
                <img
                  loading="lazy"
                  className="character"
                  alt="Female Doctor"
                  src="https://cdn6.findmyshift.com/images/features/industries/female-doctor_x1.png"
                />
              </span>
              <span className="text">Hospitals, medical &amp; care providers</span>
            </a>
            <a href="/professional-services-scheduling">
              <span className="character-container">
                <img
                  loading="lazy"
                  className="character"
                  alt="Handyman"
                  src="https://cdn6.findmyshift.com/images/features/industries/handyman_x1.png"
                />
              </span>
              <span className="text">Professional services</span>
            </a>
            <a href="/retail-store-scheduling">
              <span className="character-container">
                <img
                  loading="lazy"
                  className="character"
                  alt="Retail Worker"
                  src="https://cdn6.findmyshift.com/images/features/industries/retail-worker_x1.png"
                />
              </span>
              <span className="text">Retail stores &amp; supermarkets</span>
            </a>
            <a href="/classroom-scheduling">
              <span className="character-container">
                <img
                  loading="lazy"
                  className="character"
                  alt="Student"
                  src="https://cdn6.findmyshift.com/images/features/industries/student_x1.png"
                />
              </span>
              <span className="text">Schools &amp; universities</span>
            </a>
            <a href="/security-service-scheduling">
              <span className="character-container">
                <img
                  loading="lazy"
                  className="character"
                  alt="Policeman"
                  src="https://cdn6.findmyshift.com/images/features/industries/policeman_x1.png"
                />
              </span>
              <span className="text">Security services &amp; law enforcement</span>
            </a>
            <a href="/shipping-and-transportation-scheduling">
              <span className="character-container">
                <img
                  loading="lazy"
                  className="character"
                  alt="Delivery Man"
                  src="https://cdn6.findmyshift.com/images/features/industries/delivery-man_x1.png"
                />
              </span>
              <span className="text">Shipping &amp; transportation</span>
            </a>
          </div>
        </div>
      </div>
    </>
  );
};
