import React, { useState } from 'react';
 // Import the CSS file for styles
 import { Link, useNavigate } from 'react-router-dom';
import logo from '../assets/images/logo.png';
import '../assets/Pro.css';
import axios from 'axios';

const MessageDialog = () => {
    const [isLoggedIn, setIsLoggedIn] = useState(false);
    const [userEmail, setUserEmail] = useState('');
    const navigate = useNavigate();

    const [formData, setFormData] = useState({
        staffName: '',
        currentTask: '',
        desiredStartDate: '',
        desiredEndDate: '',
        reason: '',
        additionalComments: ''
    });

    const handleChange = (e) => {
        const { name, value } = e.target;
        setFormData({
            ...formData,
            [name]: value
        });
    };

    const handleLogin = () => {
        setIsLoggedIn(true);
        setUserEmail('user@example.com');
        navigate('/home');
    };

    const handleLogout = () => {
        setIsLoggedIn(false);
        setUserEmail('');
        navigate('/');
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        try {
            const response = await axios.post('http://localhost:8080/api/changerequests', formData);
            console.log('Form submitted successfully:', response.data);
            // Handle successful form submission (e.g., show a success message, reset form, etc.)
            setFormData({
                staffName: '',
                currentTask: '',
                desiredStartDate: '',
                desiredEndDate: '',
                reason: '',
                additionalComments: ''
            });
            alert('Your message has send Successfully');
        } catch (error) {
            console.error('Error submitting form:', error);
            // Handle error in form submission (e.g., show an error message)
        }
    };

  


    return (
        <div className='query-whole'>
            <header className="navbar">
            <div className="logo-container">
                <Link to="/">
                    <img src={logo} alt="Logo" className="logo" />
                </Link>
            </div>
            <nav className="nav-menu">
                <ul>
                    <li className="tooltip">
                        <Link to="/">Features</Link>
                        <ul style={{ maxHeight: "651px" }}>
                            <div className="tooltiptext">See our features
                                <li className="sub-menu-item has-introduction" style={{ background: "visible" }}>
                                    <a href="dashboard" className="sub-menu-item">
                                        <i className="icon fa fa-calendar"></i>
                                        <h3>Employee scheduling</h3>
                                        <span className="introduction">Our drag &amp; drop scheduler is fast, quick to learn and free for small teams.</span>
                                    </a>
                                </li>
                                <li className="sub-menu-item has-introduction">
                                
                                    <a href="" className="sub-menu-item"><i className="icon ion ion-ios-clock-outline"></i>
                                        <h3>Time and attendance</h3><span className="introduction">Record the hours your employees are actually on-site with our free time clock station.</span>
                                    </a>
                                </li>
                                <li className="sub-menu-item has-introduction">
                                    <a href="" className="sub-menu-item"><i className="icon fa fa-bar-chart"></i>
                                        <h3>Reporting and payroll</h3><span className="introduction">Track employee hours and their costs in real-time using the data generated by your work schedule.</span>
                                    </a>
                                </li>
                                <li className="sub-menu-item has-introduction">
                                    <a href="" className="sub-menu-item"><i className="icon fa fa-bell-o"></i>
                                        <h3>Reminders and notifications</h3><span className="introduction">Send your employees automated shift reminders, shift change notifications and group messages.</span>
                                    </a>
                                </li>
                                <li className="sub-menu-item has-introduction">
                                    <a href="" className="sub-menu-item"><i className="icon ion ion-android-checkbox-outline"></i>
                                        <h3>Time off management</h3><span className="introduction">Manage time off easily with online requests, assistant managers, notifications and allowance tracking.</span>
                                    </a>
                                </li>
                            </div>
                        </ul>
                    </li>
                    <li className="tooltip">
                        <Link to="/pricing">Pricing</Link>
                        <ul>
                            <span className="tooltiptext">View pricing details
                                <li className="sub-menu-item has-introduction">
                                    <a href="/pricing" className="sub-menu-item"><i className="icon fa fa-rocket"></i>
                                        <h3>Pricing plans</h3><span className="introduction">Choose a pricing plan that works for your team.</span>
                                    </a>
                                </li>
                                <li className="sub-menu-item has-introduction">
                                    <a href="/pricing" className="sub-menu-item"><i className="icon fa fa-gift"></i>
                                        <h3>Free plan for small teams</h3><span className="introduction">Findmyshift will always be free for small teams of up to 5 employees.</span>
                                    </a>
                                </li>
                                <li className="sub-menu-item has-introduction">
                                    <a href="/pricing" className="sub-menu-item"><i className="icon ion ion-ios-clock-outline"></i>
                                        <h3>Free time clock software</h3><span className="introduction">Free, unrestricted access to our web-based time clock system to help track employee hours.</span>
                                    </a>
                                </li>
                                <li className="sub-menu-item has-introduction">
                                    <a href="/pricing" className="sub-menu-item"><i className="icon fa fa-heart-o"></i>
                                        <h3>Try it free for 60 days</h3><span className="introduction">All features are free for your first 60 days. No credit cards, no mailing lists, no surprises.</span>
                                    </a>
                                </li>
                            </span>
                        </ul>
                    </li>
                    <li className="tooltip">
                        <Link to="/Layout">Help</Link>
                        <ul>
                            <span className="tooltiptext">Get support
                                <li className="sub-menu-item has-introduction">
                                    <a href="/Layout" className="sub-menu-item"><i className="icon fa fa-life-ring"></i>
                                        <h3>Knowledge base</h3><span className="introduction">Search for answers to some of the most frequently asked questions.</span>
                                    </a>
                                </li>
                                <li className="sub-menu-item has-introduction">
                                    <a href="/Layout" className="sub-menu-item"><i className="icon ion ion-social-youtube-outline"></i>
                                        <h3>Video guides and webinars</h3><span className="introduction">Watch how it's done (from setup to scheduling) with our step-by-step video guides.</span>
                                    </a>
                                </li>
                                <li className="sub-menu-item has-introduction">
                                    <a href="javascript:void(0);" onClick={() => alert('Contact support')} className="sub-menu-item last">
                                        <i className="icon fa fa-comments-o"></i>
                                        <h3>Contact support</h3><span className="introduction">Call, chat and email our support team between 12am and 10pm (BST), Monday to Friday.</span>
                                    </a>
                                </li>
                            </span>
                        </ul>
                    </li>
                    <li className="tooltip">
                        <Link to="/dashboard">Demo</Link>
                        <span className="tooltiptext">Try the demo</span>
                    </li>
                    {isLoggedIn ? (
                        <li className="tooltip">
                            <span className="tooltiptext">
                                Logged in as {userEmail}
                                <button onClick={handleLogout} className="logout-button">Logout</button>
                            </span>
                        </li>
                    ) : (
                        <li className="tooltip">
                            <Link to="/login" onClick={handleLogin}>Log in</Link>
                            <span className="tooltiptext">Access your account</span>
                        </li>
                    )}
                    <li className="highlight tooltip">
                        <Link to="/dashboard">Create a schedule</Link>
                        <span className="tooltiptext">Start scheduling</span>
                    </li>
                </ul>
            </nav>
        </header>
        <div className="query-box">
                <h2>Request Schedule Change</h2>
                <form id="schedule-change-form" onSubmit={handleSubmit}>
                    <div className="form-group">
                        <label htmlFor="staff-name">Your Name:</label>
                        <input
                            type="text"
                            id="staff-name"
                            name="staffName"
                            value={formData.staffName}
                            onChange={handleChange}
                            placeholder="Enter your name"
                            required
                        />
                    </div>

                    <div className="form-group">
                        <label htmlFor="current-task">Current Task/Shift:</label>
                        <input
                            type="text"
                            id="current-task"
                            name="currentTask"
                            value={formData.currentTask}
                            onChange={handleChange}
                            placeholder="Describe your current task/shift"
                            required
                        />
                    </div>

                    <div className="form-group">
                        <label htmlFor="desired-start-date">Desired Start Date:</label>
                        <input
                            type="date"
                            id="desired-start-date"
                            name="desiredStartDate"
                            value={formData.desiredStartDate}
                            onChange={handleChange}
                            required
                        />
                    </div>

                    <div className="form-group">
                        <label htmlFor="desired-end-date">Desired End Date:</label>
                        <input
                            type="date"
                            id="desired-end-date"
                            name="desiredEndDate"
                            value={formData.desiredEndDate}
                            onChange={handleChange}
                        />
                    </div>

                    <div className="form-group">
                        <label htmlFor="reason">Reason for Change:</label>
                        <textarea
                            id="reason"
                            name="reason"
                            value={formData.reason}
                            onChange={handleChange}
                            placeholder="Explain why you need this change"
                            rows="4"
                            required
                        />
                    </div>

                    <div className="form-group">
                        <label htmlFor="additional-comments">Additional Comments:</label>
                        <textarea
                            id="additional-comments"
                            name="additionalComments"
                            value={formData.additionalComments}
                            onChange={handleChange}
                            placeholder="Any other information"
                            rows="4"
                        />
                    </div>

                    <button type="submit">Submit Request</button>
                </form>
            </div>
        </div>

         
    );
};

export default MessageDialog;
